# name: Playwright Tests
# on:
#   push:
#     branches: [ main, master ]
#   pull_request:
#     branches: [ main, master ]
# jobs:
#   test:
#     timeout-minutes: 60
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v4
#     - uses: actions/setup-node@v4
#       with:
#         node-version: lts/*
#     - name: Install dependencies
#       run: npm ci
#     - name: Install Playwright Browsers
#       run: npx playwright install --with-deps
#     - name: Run Playwright tests
#       run: npx playwright test tests/e2e # Adjusted path to match your structure
#     - uses: actions/upload-artifact@v4
#       if: ${{ !cancelled() }}
#       with:
#         name: playwright-report
#         path: tests/e2e/playwright-report/ # Ensures the report matches your structure
#         retention-days: 30

# name: Playwright Tests
# on:
#   push:
#     branches: [ main, master ]
#   pull_request:
#     branches: [ main, master ]
# jobs:
#   test:
#     timeout-minutes: 60
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v4
#     - uses: actions/setup-node@v4
#       with:
#         node-version: lts/*
#     - name: Install dependencies
#       run: npm ci
#     - name: Install Playwright Browsers
#       run: npx playwright install --with-deps
#     - name: Create Report Directory
#       run: mkdir -p tests/e2e/playwright-report
#     - name: Run Playwright tests
#       run: npx playwright test tests/e2e # Adjust path 
#     - uses: actions/upload-artifact@v4
#       if: ${{ !cancelled() }}
#       with:
#         name: playwright-report
#         path: tests/e2e/playwright-report/
#         retention-days: 30

name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: project-2-watchlist-maker  
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: create env file
      run: |
        touch .env
        echo MONGODB_URI=${{ secrets.MONGODB_URI }} >> .env
        echo REDISCLOUD_URL=${{ secrets.REDISCLOUD_URL }} >> .env
        echo NODE_ENV=${{ secrets.NODE_ENV }} >> .env
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Create Report Directory
      run: mkdir -p ${GITHUB_WORKSPACE}/tests/e2e/playwright-report
    - name: Run Playwright tests
      run: npx playwright test ${GITHUB_WORKSPACE}/tests/e2e/watchlist.spec.js
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: ${GITHUB_WORKSPACE}/tests/e2e/playwright-report/
        retention-days: 30

